### PR TITLE
change package.json location and delete npm log

### PR DESCRIPTION
**Pull request by fernandoneto**
Change the locations of package.json (must be on root path).
delete the npm log

### CODE REVIEW

**Comment by marcospgp** [comment]
The log is unnecessary indeed!

 However the package.json is already on the root directory of the server, and seen as the two folders are basically two different projects (the extension and server's files will be on different places) there is no point in putting it outside of the server folder.

 Thanks :smiley:

**Comment by fernandoneto** [comment]
if they are dif projects create dif repos...... :)

**Comment by marcospgp** [comment]
too lazy for that! :+1:

**Comment by fernandoneto** [comment]
ok...... keep the good work

**Comment by marcospgp** [comment]
Thanks a lot!

**Comment by cusspvz** [comment]
Why won't you both leave current structure ( server / structure ) and use an online and free service for exchanging messages between clients/extension?

You could use [Pusher](https://www.pusher.com), they have a "free" plan that should meet this project needs.

captura de ecra 2015-02-14 as 01 41 14

**Comment by marcospgp** [comment]
That is a really awesome idea! The 20 max connections are per channel or globally?

**Comment by cusspvz** [comment]
Yup, but you can turn arround that limit by allowing your users to set up a pusher account.

**Pull request merged**
